const pdfjsLib = window["pdfjs-dist/build/pdf"];
pdfjsLib.GlobalWorkerOptions.workerSrc =
  "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
if (location.protocol === "file:") {
  pdfjsLib.disableWorker = true;
}

const state = {
  pdfs: [],
  activePdfId: null,
  recording: false,
  recordingSession: null,
  queue: [],
  logs: [],
  mode: "realtime",
  showMarkers: false,
  adjustMode: false,
  selectedAnnotationId: null,
  onlinePrompted: false,
  navTab: "outline",
  tapFocusHintShown: false,
  activeSessionId: null,
  sessionState: null,
  activePageIndex: 0,
  linkReturn: null,
  isPinching: false,
  settings: {
    sttProvider: "native",
    sttModel: "whisper-1",
    sttKey: "",
    sttPrompt: "",
    aiProvider: "openai",
    aiModel: "gpt-4o-mini",
    aiKey: "",
    customPrompt: "",
    mockAI: false,
    tapFocus: false,
    theme: "system",
    ocrEnabled: false
  }
};

const elements = {
  pdfInput: document.getElementById("pdfInput"),
  uploadPdf: document.getElementById("uploadPdf"),
  pdfList: document.getElementById("pdfList"),
  pdfMenuToggle: document.getElementById("pdfMenuToggle"),
  pdfMenu: document.getElementById("pdfMenu"),
  activePdfLabel: document.getElementById("activePdfLabel"),
  overflowToggle: document.getElementById("overflowToggle"),
  overflowMenu: document.getElementById("overflowMenu"),
  viewerArea: document.getElementById("viewerArea"),
  emptyState: document.getElementById("emptyState"),
  settingsToggle: document.getElementById("settingsToggle"),
  settingsPanel: document.getElementById("settingsPanel"),
  micButton: document.getElementById("micButton"),
  toastContainer: document.getElementById("toastContainer"),
  modalOverlay: document.getElementById("modalOverlay"),
  modalTitle: document.getElementById("modalTitle"),
  modalBody: document.getElementById("modalBody"),
  modalActions: document.getElementById("modalActions"),
  queueIndicator: document.getElementById("queueIndicator"),
  processBatch: document.getElementById("processBatch"),
  progressLabel: document.getElementById("progressLabel"),
  tapFocusButton: document.getElementById("tapFocusButton"),
  toggleAdjust: document.getElementById("toggleAdjust"),
  commitAdjust: document.getElementById("commitAdjust"),
  adjustToolbar: document.getElementById("adjustToolbar"),
  snapToText: document.getElementById("snapToText"),
  freeBox: document.getElementById("freeBox"),
  loadingOverlay: document.getElementById("loadingOverlay"),
  connectionDot: document.getElementById("connectionDot"),
  connectionIcon: document.getElementById("connectionIcon"),
  connectionLabel: document.getElementById("connectionLabel"),
  downloadSingle: document.getElementById("downloadSingle"),
  downloadMerged: document.getElementById("downloadMerged"),
  downloadZip: document.getElementById("downloadZip"),
  toggleSidebar: document.getElementById("toggleSidebar"),
  sidebarScrim: document.getElementById("sidebarScrim"),
  closeSidebar: document.getElementById("closeSidebar"),
  settingsScrim: document.getElementById("settingsScrim"),
  logsScrim: document.getElementById("logsScrim"),
  logsPanel: document.getElementById("logsPanel"),
  logsToggle: document.getElementById("logsToggle"),
  logsClose: document.getElementById("logsClose"),
  logsList: document.getElementById("logsList"),
  logsCount: document.getElementById("logsCount"),
  logsMeta: document.getElementById("logsMeta"),
  jumpBack: document.getElementById("jumpBack"),
  jumpBackText: document.getElementById("jumpBackText"),
  jumpBackReturn: document.getElementById("jumpBackReturn"),
  jumpBackClose: document.getElementById("jumpBackClose"),
  pageJumpInput: document.getElementById("pageJumpInput"),
  pageJumpGo: document.getElementById("pageJumpGo"),
  searchInput: document.getElementById("searchInput"),
  searchGo: document.getElementById("searchGo"),
  searchResults: document.getElementById("searchResults"),
  outlineTab: document.getElementById("outlineTab"),
  thumbTab: document.getElementById("thumbTab"),
  outlinePanel: document.getElementById("outlinePanel"),
  thumbPanel: document.getElementById("thumbPanel"),
  outlineList: document.getElementById("outlineList"),
  thumbnailList: document.getElementById("thumbnailList"),
  resetSession: document.getElementById("resetSession"),
  resetSessionPanel: document.getElementById("resetSessionPanel"),
  saveSettings: document.getElementById("saveSettings"),
  clearOffline: document.getElementById("clearOffline"),
  storageUsage: document.getElementById("storageUsage"),
  themeToggle: document.getElementById("themeToggle"),
  themeToggleIcon: document.getElementById("themeToggleIcon"),
  themeTogglePanel: document.getElementById("themeTogglePanel"),
  themeTogglePanelIcon: document.getElementById("themeTogglePanelIcon"),
  themeTogglePanelLabel: document.getElementById("themeTogglePanelLabel"),
  modeRealtime: document.getElementById("modeRealtime"),
  modeBatch: document.getElementById("modeBatch"),
  sttProviderSelect: document.getElementById("sttProviderSelect"),
  sttModel: document.getElementById("sttModel"),
  sttKey: document.getElementById("sttKey"),
  sttPrompt: document.getElementById("sttPrompt"),
  aiProvider: document.getElementById("aiProvider"),
  aiModel: document.getElementById("aiModel"),
  aiKey: document.getElementById("aiKey"),
  customPrompt: document.getElementById("customPrompt"),
  mockToggle: document.getElementById("mockToggle"),
  ocrToggle: document.getElementById("ocrToggle"),
  ocrRun: document.getElementById("ocrRun"),
  processBatchMenu: document.getElementById("processBatchMenu")
};

const dbName = "voxmark-db";
const dbVersion = 2;
let db;

function getActivePdf() {
  return state.pdfs.find((pdf) => pdf.id === state.activePdfId);
}
