const pdfjsLib = window["pdfjs-dist/build/pdf"];
pdfjsLib.GlobalWorkerOptions.workerSrc =
  "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
if (location.protocol === "file:") {
  pdfjsLib.disableWorker = true;
}

const DEFAULT_SETTINGS = {
  sttProvider: "native",
  sttModel: "whisper-1",
  sttKey: "",
  sttPrompt: "",
  aiProvider: "openai",
  aiModel: "gpt-4o-mini",
  aiKey: "",
  customPrompt: "",
  colorPalette: [
    { name: "Yellow", color: "#f9de6f" },
    { name: "Blue", color: "#6f9fe6" },
    { name: "Red", color: "#e56b6b" },
    { name: "Green", color: "#6dbb8a" },
    { name: "Purple", color: "#b1a0d4" },
    { name: "Pink", color: "#d9a0b5" }
  ],
  mockAI: false,
  tapFocus: false,
  theme: "system",
  ocrEnabled: false,
  invertPdf: false
};

const state = {
  pdfs: [],
  activePdfId: null,
  recording: false,
  recordingSession: null,
  queue: [],
  logs: [],
  mode: "realtime",
  showMarkers: false,
  adjustMode: false,
  selectedAnnotationId: null,
  onlinePrompted: false,
  navTab: "outline",
  tapFocusHintShown: false,
  activeSessionId: null,
  sessionState: null,
  activePageIndex: 0,
  linkReturn: null,
  isPinching: false,
  searchResults: [],
  activeSearchIndex: -1,
  searchTerm: "",
  settings: { ...DEFAULT_SETTINGS }
};

const elements = {
  pdfInput: document.getElementById("pdfInput"),
  uploadPdf: document.getElementById("uploadPdf"),
  pdfList: document.getElementById("pdfList"),
  pdfMenuToggle: document.getElementById("pdfMenuToggle"),
  pdfMenu: document.getElementById("pdfMenu"),
  activePdfLabel: document.getElementById("activePdfLabel"),
  overflowToggle: document.getElementById("overflowToggle"),
  overflowMenu: document.getElementById("overflowMenu"),
  queueToggle: document.getElementById("queueToggle"),
  searchToggle: document.getElementById("searchToggle"),
  searchScrim: document.getElementById("searchScrim"),
  viewerArea: document.getElementById("viewerArea"),
  emptyState: document.getElementById("emptyState"),
  settingsToggle: document.getElementById("settingsToggle"),
  settingsPanel: document.getElementById("settingsPanel"),
  micButton: document.getElementById("micButton"),
  toastContainer: document.getElementById("toastContainer"),
  modalOverlay: document.getElementById("modalOverlay"),
  modalTitle: document.getElementById("modalTitle"),
  modalBody: document.getElementById("modalBody"),
  modalActions: document.getElementById("modalActions"),
  queueIndicator: document.getElementById("queueIndicator"),
  processBatch: document.getElementById("processBatch"),
  progressLabel: document.getElementById("progressLabel"),
  zoomInput: document.getElementById("zoomInput"),
  tapFocusButton: document.getElementById("tapFocusButton"),
  toggleAdjust: document.getElementById("toggleAdjust"),
  commitAdjust: document.getElementById("commitAdjust"),
  adjustToolbar: document.getElementById("adjustToolbar"),
  snapToText: document.getElementById("snapToText"),
  freeBox: document.getElementById("freeBox"),
  loadingOverlay: document.getElementById("loadingOverlay"),
  connectionDot: document.getElementById("connectionDot"),
  connectionIcon: document.getElementById("connectionIcon"),
  connectionLabel: document.getElementById("connectionLabel"),
  downloadSingle: document.getElementById("downloadSingle"),
  downloadMerged: document.getElementById("downloadMerged"),
  downloadZip: document.getElementById("downloadZip"),
  header: document.querySelector("header"),
  toggleSidebar: document.getElementById("toggleSidebar"),
  sidebarScrim: document.getElementById("sidebarScrim"),
  settingsScrim: document.getElementById("settingsScrim"),
  logsScrim: document.getElementById("logsScrim"),
  logsPanel: document.getElementById("logsPanel"),
  logsToggle: document.getElementById("logsToggle"),
  logsClose: document.getElementById("logsClose"),
  logsClear: document.getElementById("logsClear"),
  logsList: document.getElementById("logsList"),
  logsCount: document.getElementById("logsCount"),
  logsMeta: document.getElementById("logsMeta"),
  queueScrim: document.getElementById("queueScrim"),
  queuePanel: document.getElementById("queuePanel"),
  queueClose: document.getElementById("queueClose"),
  queueList: document.getElementById("queueList"),
  queueMeta: document.getElementById("queueMeta"),
  queueRetryAll: document.getElementById("queueRetryAll"),
  jumpBack: document.getElementById("jumpBack"),
  jumpBackText: document.getElementById("jumpBackText"),
  jumpBackReturn: document.getElementById("jumpBackReturn"),
  jumpBackClose: document.getElementById("jumpBackClose"),
  pageJumpInput: document.getElementById("pageJumpInput"),
  pageJumpGo: document.getElementById("pageJumpGo"),
  pageJumpTotal: document.getElementById("pageJumpTotal"),
  searchInput: document.getElementById("searchInput"),
  searchClear: document.getElementById("searchClear"),
  searchGo: document.getElementById("searchGo"),
  searchPrev: document.getElementById("searchPrev"),
  searchNext: document.getElementById("searchNext"),
  searchResults: document.getElementById("searchResults"),
  outlineTab: document.getElementById("outlineTab"),
  thumbTab: document.getElementById("thumbTab"),
  outlinePanel: document.getElementById("outlinePanel"),
  thumbPanel: document.getElementById("thumbPanel"),
  outlineList: document.getElementById("outlineList"),
  thumbnailList: document.getElementById("thumbnailList"),
  resetSession: document.getElementById("resetSession"),
  resetSessionPanel: document.getElementById("resetSessionPanel"),
  resetApp: document.getElementById("resetApp"),
  resetAppPanel: document.getElementById("resetAppPanel"),
  saveSettings: document.getElementById("saveSettings"),
  clearOffline: document.getElementById("clearOffline"),
  storageUsage: document.getElementById("storageUsage"),
  themeToggle: document.getElementById("themeToggle"),
  themeToggleIcon: document.getElementById("themeToggleIcon"),
  themeTogglePanel: document.getElementById("themeTogglePanel"),
  themeTogglePanelIcon: document.getElementById("themeTogglePanelIcon"),
  themeTogglePanelLabel: document.getElementById("themeTogglePanelLabel"),
  modeRealtime: document.getElementById("modeRealtime"),
  modeBatch: document.getElementById("modeBatch"),
  sttProviderSelect: document.getElementById("sttProviderSelect"),
  sttModel: document.getElementById("sttModel"),
  sttKey: document.getElementById("sttKey"),
  sttPrompt: document.getElementById("sttPrompt"),
  aiProvider: document.getElementById("aiProvider"),
  aiModel: document.getElementById("aiModel"),
  aiKey: document.getElementById("aiKey"),
  customPrompt: document.getElementById("customPrompt"),
  paletteList: document.getElementById("paletteList"),
  paletteAdd: document.getElementById("paletteAdd"),
  paletteSaveDefault: document.getElementById("paletteSaveDefault"),
  paletteRestoreDefault: document.getElementById("paletteRestoreDefault"),
  mockToggle: document.getElementById("mockToggle"),
  ocrToggle: document.getElementById("ocrToggle"),
  ocrRun: document.getElementById("ocrRun"),
  invertPdfToggle: document.getElementById("invertPdfToggle"),
  processBatchMenu: document.getElementById("processBatchMenu")
};

const dbName = "voxmark-db";
const dbVersion = 3;
let db;

function getActivePdf() {
  return state.pdfs.find((pdf) => pdf.id === state.activePdfId);
}
